### PR TITLE
Feature inss individual insolvency register initial

### PR DESCRIPTION
**Pull request by SSYerawar**

### CODE REVIEW

**Comment by timnaish-insolvency** [comment]
There are binaries in this commit. Please remove them - I suggest you add them to a .gitignore file.

**Comment by SSYerawar** [comment]
> There are binaries in this commit. Please remove them - I suggest you add them to a .gitignore file.
Done

**Comment by spartacus72** [comment]
@SSYerawar your gitignore file appears to be for a node project and not a .net solution.  The bin and obj folders need to be ignored.  also the obj folder is still in the commit.  it should be removed.

**Comment by SSYerawar** [comment]
@Jeffrey ***@***.***> just wait .I  have included Vs Bin and OBJ for some reasons it's not picking up .

If you scroll you will find the entries . Visual studio and visual studio code .

I will update you when it's ready to approve .

Please refrain from doing anything now. Thank you




Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by spartacus72 — APPROVED** [review]

**Comment by timnaish-insolvency** [comment]
@SSYerawar I've set this back to draft status. Once you're ready for review, please set to Ready for review (there's still .vs solutions files in the PR).

**Comment by SSYerawar** [comment]
> There are binaries in this commit. Please remove them - I suggest you add them to a .gitignore file.

hi Tim , Can you please review again and let me know if this is okay .

**Comment by timnaish-insolvency** [comment]
@SSYerawar Contents look OK, but we operate [GitFlow ](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)at INSS (yeah, I know), so this feature branch should be PR'd into develop rather than main. 
FYI @spartacus72

**Pull request merged**
